name: Build

on:
  workflow_call:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 8
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build
      - uses: codecov/codecov-action@v4
        with:
          verbose: true
