name: Build

on:
  workflow_call:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    uses: jensborch/workflows/.github/workflows/gradle-build.yml@main
    with:
      java-version: 8
