name: Publish

on:
  pull_request:
    branches: [master]
    types: [closed]

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    if: contains(github.head_ref, 'releases/') && github.event.pull_request.merged == true && github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 8
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.get_version.outputs.version }}
          body: |
            Release version ${{ steps.get_version.outputs.version }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToSonatype
        env:
          ORG_GRADLE_PROJECT_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
