name: Publish

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  call-workflow:
    uses: jensborch/workflows/.github/workflows/gradle-publish.yml@main
    secrets: inherit
    permissions:
      contents: write
    with:
      java-version: 8
