name: Release

on:
  push:
    branches:
      - 'releases/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    if: github.event.created
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 8
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Set Version
        run: |
          echo "version=$(echo ${{ github.ref }} | sed 's/refs\/heads\/releases\///')" >> $GITHUB_ENV
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Bump Version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bumpVersion -Prelease.version=${{ env.version }}
      - name: Commit and Push Changes
        run: |
          git commit -am "Bump version to ${{ env.version }}"
          git tag -a v${{ env.version }} -m "Release version ${{ env.version }}"
          git push origin release-${{ env.version }} --follow-tags
      - name: Create Pull Request
        run: gh pr create -B master --title 'Release version ${{ env.version }}' --body 'This pull request bumps the version to ${{ env.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          arguments: bumpVersion -Prelease.version=${{ env.version }}
      - name: Commit and Push Changes
        run: |
          git commit -am "Bump version to ${{ env.version }}"
          git tag -a v${{ env.version }} -m "Release version ${{ env.version }}"
          git push origin release-${{ env.version }} --follow-tags
      - name: Create Pull Request
        run: gh pr create -B master --title 'Release version ${{ env.version }}' --body 'This pull request bumps the version to ${{ env.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
