name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version"
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 8
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Configure Git Author
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Create Release Branch
        run: |
          git checkout -b release-${{ github.event.inputs.version }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Bump Version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bumpVersion -Prelease.version=${{ github.event.inputs.version }}
      - name: Commit and Push Changes
        run: |
          git commit -am "Bump version to ${{ github.event.inputs.version }}"
          git tag -a v${{ github.event.inputs.version }} -m "Release version ${{ github.event.inputs.version }}"
          git push origin release-${{ github.event.inputs.version }} --follow-tags
      - name: Create Pull Request
        run: gh pr create -B master --title 'Release version ${{ github.event.inputs.version }}' --body 'This pull request bumps the version to ${{ github.event.inputs.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Call Build workflow
        uses: jensborch/rsql-parser/.github/workflows/build.yml@main
