name: Release

on:
  push:
    branches:
      - 'releases/**'

jobs:
  call-workflow:
    uses: jensborch/workflows/.github/workflows/gradle-release.yml@main
    secrets: inherit
    with:
        java-version: 8
