name: Scorecard supply-chain security

on:
  # For Branch-Protection check. Only the default branch is supported. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  branch_protection_rule:
  # To guarantee Maintained check is occasionally updated. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained
  schedule:
    - cron: '34 3 * * 2'
  push:
    branches: ['master']

jobs:
  call-workflow:
    uses: jensborch/workflows/.github/workflows/scorecard.yml@main
    permissions:
      actions: read
      contents: read
      deployments: read
      packages: read
      security-events: write
      id-token: write

